### ISSUE TITLE
Make .nib files compatible with OS X Mavericks

### ISSUE THREAD

**Issue by oliveratgithub** [oliveratgithub/ToeTag#4]
The .nib Controller Views are still set for OS X 10.5 compatibility. They should be adjusted for OS X 10.9 compatibility, in terms of getting the Mavericks version up and running.

**Comment by ellmo** [comment]
Hello,

I just downloaded ToeTag and started learning how to create Q1 maps. Being a long time Doom mapper I thought I'll take a whack (again) at the magnificent Quake.

Problem is I'm running 10.9 – is ToeTag currently not supporting this OSX version at all? As soon as I select geometry with any texture WAD loaded the app crashes. Can provide logs, if this is something you haven't encountered before.

**Comment by oliveratgithub** [comment]
Hi @ellmo,

Yes I am aware of this bug which I encountered too when playing around with a map. As far as the analysis has been done so far, it's because the most recent ToeTag release is not optimized for OSX 10.7+ (including 10.9+) - this means, it has not implemented a proper Garbage Collection for memory cleanup and thus crashes really quickly when it shouldn't.

I was trying to find the issue with loading the WAD files, but after 1 or 2 hours of investigating and debugging - by not understanding too much of the code, me and a friend "postponed" that task for later ;) I would be happy to have someone with a bit more knowledge in this kind of stuff to help optimizing ToeTag for OS X 10.9...

Sorry for not having better news for that in the meantime. At least you can open existing MAP files with textures by using the current code base on GitHub - but it will fail once you get to the WAD browser :(

**Comment by oliveratgithub** [comment]
Closing - Project abandoned.
